import 'dart:math';

class AppQoutes {
  static var random = new Random();
  static List<String> qoutesList = [
    "In youth we learn in age we understand.",
    "Youth has no age.",
    "You should not consider a man's age but his acts.",
    "If you tell people where to go, but not how to get there, you'll be amazed at the results.",
    "If you set goals and go after them with all the determination you can muster, your gifts will take you places that will amaze you.",
    "Nobody in life gets exactly what they thought they were going to get. But if you work really hard and you're kind, amazing things will happen.",
    " When you have confidence, you can have a lot of fun. And when you have fun, you can do amazing things.",
    "The thing that is really hard, and really amazing, is giving up on being perfect and beginning the work of becoming yourself.",
    "If there was an observer on Mars, they would probably be amazed that we have survived this long.",
    "With love, you should go ahead and take the risk of getting hurt because love is an amazing feeling.",
    "If you dream of something worth doing and then simply go to work on it and don't think anything of personalities, or emotional conflicts, or of money, or of family distractions it is amazing how quickly you get through those 5,000 steps.",
    "It's amazing how, over time, a person's perspective can be altered.",
    "The body is an amazing machine... If you eat the right things your body will perform incredibly well! Amazement awaits us at every corner.",
    "The body can do amazing things in a situation when it is really called for.",
    "Everything that has happened to me has been amazing and surprising.",
    "For every minute you remain angry, you give up sixty seconds of peace of mind.",
    "Anger and intolerance are the enemies of correct understanding.",
    "Speak when you are angry and you will make the best speech you will ever regret.",
    "Man should forget his anger before he lies down to sleep.",
    "Every time you get angry, you poison your own system.",
    "Anger is a wind which blows out the lamp of the mind.",
    "Revenge is often like biting a dog because the dog bit you.",
    "Always write angry letters to your enemies. Never mail them.",
    "Keep cool anger is not an argument.",
    "Anger is as a stone cast into a wasp's nest.",
    "Anger has a way of seeping into every other emotion and planting itself in there.",
    "Anger is a momentary madness, so control your passion or it will control you.",
    "Keep your temper. A decision made in anger is never sound.",
    "Anger's not a good emotion.",
    "Whatever good things we build end up building us.",
    "Less is more.",
    "Choosing to be positive and having a grateful attitude is going to determine how you're going to live your life.",
    "My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.",
    "Attitude is a little thing that makes a big difference.",
    "Character is the result of two things: mental attitude and the way we spend our time.",
    "Our attitude towards others determines their attitude towards us.",
    "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.",
    "Good humor is one of the best articles of dress one can wear in society.",
    "Attitude is everything.",
    "Our attitude toward life determines life's attitude towards us.",
    "Funny is an attitude.",
    "There are no menial jobs, only menial attitudes.",
    "The only disability in life is a bad attitude.",
    "She got her looks from her father. He's a plastic surgeon.",
    "Personal beauty is a greater recommendation than any letter of reference.",
    "Beauty has a lot to do with character.",
    "Beauty is the promise of happiness.",
    "Beauty is power a smile is its sword.",
    "Beauty is only temporary, but your mind lasts you a lifetime.",
    "Things turn out best for the people who make the best of the way things turn out.",
    "The best way to find out if you can trust somebody is to trust them.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Learn to say 'no' to the good so you can say 'yes' to the best.",
    "The best revenge is to be unlike him who performed the injury.",
    "The best way to predict the future is to create it.",
    "Nobody who ever gave his best regretted it.",
    "Since we live in this world, we have to do our best for this world.",
    "First gain the victory and then make the best use of it you can.",
    "Just do what you do best.",
    " Always do your best. What you plant now, you will harvest later.",
    "The best thing to hold onto in life is each other.",
    "The trees that are slow to grow bear the best fruit.",
    "The best way out is always through.",
    "My best friend is the one who brings out the best in me.",
    "If you're doing your best, you won't have any time to worry about failure.",
    "The best way to make your dreams come true is to wake up.",
    "The best way to pay for a lovely moment is to enjoy it.",
    "Our best successes often come after our greatest disappointments.",
    "Do right. Do your best. Treat others as you want to be treated.",
    "Just do the best you can. No one can do more than that.",
    "The best preparation for tomorrow is doing your best today.",
    "The best way to predict the future is to invent it.",
    "We must stop thinking of the individual and start thinking about what is best for society.",
    "Expect the best, plan for the worst, and prepare to be surprised.",
    " The best work is not what is most difficult for you it is what you do best.",
    " The only failure one should fear, is not hugging to the purpose they see as best.",
    "I have made the choices that work best for me. I know I cannot please everyone, and that's fine.",
    "Things are never quite as scary when you've got a best friend.",
    "Youth is the best time to be rich, and the best time to be poor.",
    "A man's best fortune, or his worst, is his wife.",
    "Humor is one of the best ingredients of survival.",
    " Having lots of siblings is like having built-in best friends.",
    "Patience is the best remedy for every trouble.",
    "Walking is man's best medicine.",
    "  Your best teacher is your last mistake.",
    " Time is generally the best doctor.",
    "The best way to have a good idea is to have a lot of ideas.",
    "He who laughs most, learns best.",
    "The best way to remember your wife's birthday is to remember it once.",
    "My siblings are my best friends.",
    "If you want to be the best, you have to do things that other people aren't willing to do.",
    "Life is best when you are in love.",
    "What I love best in life is new starts.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "All lasting business is built on friendship.",
    "When you have a dream, you’ve got to grab it and never let go",
    "Nothing is impossible. The word itself says ‘I’m possible!",
    "There is nothing impossible to they who will try.",
    "Life has got all those twists and turns. You’ve got to hold on tight and off you go",
    "Keep your face always toward the sunshine, and shadows will fall behind you our define your own life.",
    "Don’t let other people write your script.",
    "You are never too old to set another goal or to dream a new dream Spread love everywhere you go .",
    "You don’t always need a plan.",
    "Sometimes you just need to breathe, trust, let go and see what happens",
    "You can be everything.",
    "You can be the infinite amount of things that people are.",
    "It is during our darkest moments that we must focus to see the light Believe you can and you’re halfway there.",
    "Weaknesses are just strengths in the wrong environment Just don’t give up trying to do what you really want to do.",
    "Where there is love and inspiration, I don’t think you can go wrong",
    "In a gentle way, you can shake the world",
    "Wake up determined, go to bed satisfied",
    "Nobody built like you, you design yourself",
    "Live your beliefs and you can turn the world around",
    "Life is like riding a bicycle. To keep your balance, you must keep moving",
    "If you don’t like the road you’re walking, start paving another one!",
    "We generate fears while we sit. We overcome them by action",
    "You do not find the happy life. You make it.",
    "I will not let anyone scare me out of my full potential",
    "Never bend your head. Always hold it high. Look the world straight in the eye.",
    "Let love rule",
    "The power of imagination makes us infinite.",
    "If my mind can conceive it, if my heart can believe it, then I can achieve it.",
    "Today’s goals: Coffee and kindness. Maybe two coffees, and then kindness.",
    "An early-morning walk is a blessing for the whole day.",
    "Lose an hour in the morning, and you will spend all day looking for it.",
    "All our dreams can come true, if we have the courage to pursue them",
    "The secret of getting ahead is getting started",
    "The best time to plant a tree was 20 years ago. The second best time is now",
    "It’s hard to beat a person who never gives up",
    "If people are doubting how far you can go, go so far that you can’t hear them anymore",
    "Everything you can imagine is real.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us",
    "Do one thing every day that scares you.",
    "Happiness is not something ready made. It comes from your own actions",
    "Whatever you are, be a good one",
    " Impossible is just an opinion",
    "Your passion is waiting for your courage to catch up",
    "Invest in your dreams. Grind now. Shine later",
    "Hustle in silence and let your success make the noise",
    "The hard days are what make you stronger",
    "It does not matter how slowly you go as long as you do not stop",
    "Rise up, start fresh see the bright opportunity in each day.",
    "The way to get started is to quit talking and begin doing.",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier",
    " Do not let making a living prevent you from making a life",
    "A day without laughter is a day wasted",
    "the great things always happen outside of your comfort zone",
    "If you want to live a happy life, tie it to a goal, not to people or things",
    "Turn your wounds into wisdom",
    "The healthiest response to life is joy",
    "If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles",
    "You miss 100% of the shots you don’t take",
    "Success is getting what you want, happiness is wanting what you get",
    "Don’t let yesterday take up too much of today.",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character",
    "Experience is a hard teacher because she gives the test first, the lesson afterwards",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Just one small positive thought in the morning can change your whole day.",
    "Opportunities don't happen, you create them",
    "Love your family, work super hard, live your passion.",
    "It is never too late to be what you might have been",
    "Don't let someone else's opinion of you become your reality",
    "If you’re not positive energy, you’re negative energy",
    "If you don’t risk anything, you risk even more",
    "Start where you are. Use what you have. Do what you can",
    "The two most important days in your life are the day you’re born and the day you find out why",
    "Nothing ever goes away until it teaches us what we need to know",
    "The best way out is always through",
    "If there is no struggle, there is no progress",
    "Courage is like a muscle. We strengthen it by use",
    "You’ll never get bored when you try something new. There’s really no limit to what you can do",
    "If it makes you nervous, you’re doing it right",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination",
    "Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new",
    "Life only changes when you decide to change. It may not be comfortable or easy, but it sure is worth it.",
    "We must be willing to let go of the life we planned so as to have the life that is waiting for us",
    "Everything you’ve ever wanted is on the other side of fear",
    " You get what you give",
    "Your life only gets better when you get better",
    "You experience external change only once you change internally. Start today and watch how everything around you begins to change!",
    "Happiness is not by chance, but by choice.",
    "Be the change that you wish to see in the world",
    "If I cannot do great things, I can do small things in a great way",
    "We generate fears while we sit. We overcome them by action",
    "Today’s accomplishments were yesterday’s impossibilities",
    "Light tomorrow with today!",
    "The only limit to our realization of tomorrow will be our doubts of today",
    "Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination",
    " We may encounter many defeats but we must not be defeated",
    "Hire character. Train skill.",
    "Your time is limited, so don't waste it living someone else's life.",
    "If you are not taking care of your customer, your competitor will",
    "I'd rather regret the things I've done than regret the things I haven't done.",
    "I didn't get there by wishing for it or hoping for it, but by working for it",
    "Always do your best. What you plant now, you will harvest later.",
    "Don't let the fear of losing be greater than the excitement of winning",
    "Energy and persistence conquer all things",
    "Perseverance is failing 19 times and succeeding the 20th",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    "Action is the foundational key to all success.",
    "Done is better than perfect",
    "Don't ask if your dream is crazy, ask if it's crazy enough",
    "1 make good decisions, #2 everything else."
  ];
}
